### ISSUE TITLE
NWHAK.exe can't open haks over 2,043,777 kb (about 1/3 of the op_* haks)

### ISSUE THREAD

**Issue by Txpple** [Finaldeath/overhaul#16]
NWHAK.exe can't open haks over 2,043,777 kb.  

I'm guessing you used an automation to build the haks? I get NWHak error out of memory when I try to open the larger ones over the above referenced size.

**To Reproduce**
- Go to Haks folder
- Use NWHak to try and open haks
- Haks 2,043,777KB and under open, Haks over cannot open with nwhak

**Expected behavior**
- 
All haks should be openable

**Screenshots**
<img width="645" alt="Capture" src="https://github.com/Finaldeath/overhaul/assets/62627607/24c808bf-e74e-4f57-b502-7578f57d83d7">

**Information**
 - Module name: 
 - Overhaul version: Userpatch base (8.3GB download, 19.2GB extracted), large version 0.5

**Additional context**
Windows 10 Pro with 32mb ram etc.  I think you're hitting the hak limit on those?

**Comment by Finaldeath** [comment]
Will be fixed in the next version.
